# Generated by Django 4.2.4 on 2023-09-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_message_options_room_participants_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
